# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_name', models.CharField(max_length=20)),
                ('user_information', models.CharField(max_length=255)),
                ('user_password', models.CharField(max_length=30)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
